/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.quizapp;

/**
 *
 * @author arnav
 */
public class QuizTakingFrame extends javax.swing.JFrame {

    /**
     * Creates new form QuizTakingFrame
     */
    private int quizId;
    private int currentQuestion = 0;
    private java.util.List<Question> questions = new java.util.ArrayList<>();
    private java.util.List<String> userAnswers = new java.util.ArrayList<>();
    private javax.swing.ButtonGroup answerGroup;

    public QuizTakingFrame(int quizId) {
        this.quizId = quizId;
        initComponents();
        setTitle("Taking Quiz");
        setSize(600, 400);
        setLocationRelativeTo(null);

        // Group radio buttons in code
        answerGroup = new javax.swing.ButtonGroup();
        answerGroup.add(rbtnA);
        answerGroup.add(rbtnB);
        answerGroup.add(rbtnC);
        answerGroup.add(rbtnD);

        btnSubmit.setVisible(false);

        loadQuestions();
        displayQuestion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProgress = new javax.swing.JLabel();
        lblQuestion = new javax.swing.JLabel();
        rbtnA = new javax.swing.JRadioButton();
        rbtnB = new javax.swing.JRadioButton();
        rbtnC = new javax.swing.JRadioButton();
        rbtnD = new javax.swing.JRadioButton();
        btnNext = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblProgress.setText("Question 1 of ?");

        lblQuestion.setText("Question will appear here");

        rbtnA.setText("jRadioButton1");

        rbtnB.setText("jRadioButton1");

        rbtnC.setText("jRadioButton2");

        rbtnD.setText("jRadioButton3");

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(lblProgress))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lblQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnNext)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rbtnA, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rbtnC, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rbtnD, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rbtnB, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSubmit))))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lblProgress)
                .addGap(18, 18, 18)
                .addComponent(lblQuestion)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnA)
                    .addComponent(rbtnB))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnC)
                    .addComponent(rbtnD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNext)
                    .addComponent(btnSubmit))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        String answer = getSelectedAnswer();
        userAnswers.add(answer);
        currentQuestion++;
        displayQuestion();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        userAnswers.add(getSelectedAnswer());

        try (java.sql.Connection conn = DBConnection.getConnection()) {
            String insertSubmission = "INSERT INTO submissions (student_id, quiz_id, score) VALUES (?, ?, ?)";
            java.sql.PreparedStatement pst = conn.prepareStatement(insertSubmission, java.sql.Statement.RETURN_GENERATED_KEYS);

            int score = calculateScore();
            pst.setInt(1, SessionManager.getInstance().getUserId());
            pst.setInt(2, quizId);
            pst.setInt(3, score);
            pst.executeUpdate();

            java.sql.ResultSet rs = pst.getGeneratedKeys();
            if (rs.next()) {
                int submissionId = rs.getInt(1);
                saveAnswers(conn, submissionId);
            }

            javax.swing.JOptionPane.showMessageDialog(this, "Quiz submitted! Your score: " + score + "/" + questions.size());
            new StudentFrame().setVisible(true);
            this.dispose();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuizTakingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuizTakingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuizTakingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizTakingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuizTakingFrame(1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel lblProgress;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JRadioButton rbtnA;
    private javax.swing.JRadioButton rbtnB;
    private javax.swing.JRadioButton rbtnC;
    private javax.swing.JRadioButton rbtnD;
    // End of variables declaration//GEN-END:variables
    private void loadQuestions() {
        try (java.sql.Connection conn = DBConnection.getConnection()) {
            String query = "SELECT question_id, question_text, option_a, option_b, option_c, option_d, correct_option FROM questions WHERE quiz_id = ?";
            java.sql.PreparedStatement pst = conn.prepareStatement(query);
            pst.setInt(1, quizId);
            java.sql.ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                Question q = new Question();
                q.id = rs.getInt("question_id");
                q.text = rs.getString("question_text");
                q.optionA = rs.getString("option_a");
                q.optionB = rs.getString("option_b");
                q.optionC = rs.getString("option_c");
                q.optionD = rs.getString("option_d");
                q.correct = rs.getString("correct_option");
                questions.add(q);
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error loading questions: " + e.getMessage());
        }
    }

    private void displayQuestion() {
        if (currentQuestion < questions.size()) {
            Question q = questions.get(currentQuestion);
            lblQuestion.setText(q.text);
            rbtnA.setText("A) " + q.optionA);
            rbtnB.setText("B) " + q.optionB);
            rbtnC.setText("C) " + q.optionC);
            rbtnD.setText("D) " + q.optionD);
            answerGroup.clearSelection();
            lblProgress.setText("Question " + (currentQuestion + 1) + " of " + questions.size());

            if (currentQuestion == questions.size() - 1) {
                btnNext.setVisible(false);
                btnSubmit.setVisible(true);
            }
        }
    }

    private String getSelectedAnswer() {
        if (rbtnA.isSelected()) return "A";
        if (rbtnB.isSelected()) return "B";
        if (rbtnC.isSelected()) return "C";
        if (rbtnD.isSelected()) return "D";
        return null;
    }

    private int calculateScore() {
        int score = 0;
        for (int i = 0; i < questions.size(); i++) {
            if (i < userAnswers.size() && userAnswers.get(i) != null &&
                userAnswers.get(i).equals(questions.get(i).correct)) {
                score++;
            }
        }
        return score;
    }

    private void saveAnswers(java.sql.Connection conn, int submissionId) throws java.sql.SQLException {
        String query = "INSERT INTO answers (submission_id, question_id, selected_option) VALUES (?, ?, ?)";
        java.sql.PreparedStatement pst = conn.prepareStatement(query);

        for (int i = 0; i < questions.size() && i < userAnswers.size(); i++) {
            pst.setInt(1, submissionId);
            pst.setInt(2, questions.get(i).id);
            pst.setString(3, userAnswers.get(i));
            pst.executeUpdate();
        }
    }

    static class Question {
        int id;
        String text, optionA, optionB, optionC, optionD, correct;
    }
}
